MovieApp/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='/password/password_reset_complete.html'), name='password_reset_complete'),
]

movies/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.shortcuts import redirect
from django.urls import path

from movies import views
from MovieApp import settings
from movies.models import MyUser, Movie


app_name = 'movies'
urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('login', views.LoginView.as_view(), name='loginPage'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('index', views.GetMovieView.as_view(), name='index1'),
    path('<int:movie_id>/', views.GetMovie, name='movie_page'),
    path('filteredMovies', views.FilterView.as_view(), name='filter_movies'),
    path('search', views.SearchView.as_view(), name='search'),
    # path('addMovie', views.AddMovieView.as_view(), name='add_movie_page'),
    path('addMovie', views.AddMovieView.as_view(), name='add_movie'),
    path('deleteMovie', views.deleteMovie, name='deleteMovie'),
    path('editMovie', views.EditMovieView.as_view(), name='edit_movie'),
    path('movieUpdated', views.EditMovieView.as_view(), name='edit_movie'),
    path('users', views.GetUser.as_view(), name='allUsers'),
    path('userProfile', views.ProfileView.as_view(), name='profile'),
    path('createUser', views.AddUserView.as_view(), name='createUser'),
    path('checkUser', views.LoginView.as_view(), name='check_user'),
    # path('addUser', views.SignupView.as_view(), name='add_user_page'),
    path('deleteUser', views.deleteUser, name='deleteUser'),
    path('editUser', views.EditUserView.as_view(), name='edit_user'),
    # path('userUpdated', views.EditUserView.as_view(), name='update_user'),
    path('rateMovie', views.RateMovie, name='rating'),
    path('password_reset', views.password_reset_request.as_view(), name="password_reset")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from datetime import datetime
from time import timezone

from django.contrib.auth.models import AbstractUser, User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.shortcuts import redirect, render


class MyUser(User):
    class Meta:
        proxy = True
        ordering = ('first_name',)

    @classmethod
    def getUsers(cls, id1=None):
        user_list = cls.objects.all()
        if id1:
            user_list = user_list.objects.get(id=id1)
        return user_list

    @classmethod
    def createUser(cls, username, email, fname, lname, password):
        user = cls.objects.create(username=username, email=email, firstName=fname, lastName=lname,
                                  password=password)
        user.set_password(password)
        user.save()
        return user

    @classmethod
    def deleteUserQuery(cls, id):
        user1 = User.objects.get(id=id)
        user1.delete()


class Movie(models.Model):
    name = models.CharField(max_length=300)
    thumbnail = models.ImageField(upload_to="my_folder_name")
    video_url = models.URLField()
    genre = models.CharField(max_length=200)
    short_desc = models.CharField(max_length=200)
    long_desc = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

    @classmethod
    def getMovies(cls, id1=None, title=None):
        movies_list = Movie.objects.all()
        if id1:
            movies_list = cls.objects.get(id=id1)
        if title:
            movies_list = cls.objects.get(name__icontains=title)
        return movies_list

    @classmethod
    def createMovie(cls, name, thumbnail, video_url, genre, short_desc, long_desc):
        movies = Movie.objects.create(name=name, thumbnail=thumbnail, video_url=video_url, genre=genre,
                                      short_desc=short_desc, long_desc=long_desc)
        movies.save()

    @staticmethod
    def deleteMovieQuery(id1):
        movie1 = Movie.objects.get(id=id1)
        movie1.delete()


class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, blank=False, default=1)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, blank=False, default=1)
    rate = models.IntegerField(default=5)
    created_at = models.DateTimeField(null=True, blank=True)

movies/views.py
import django.contrib.auth
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseRedirect
from django.template import loader
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Movie, MyUser


class ProfileView(LoginRequiredMixin, TemplateView):
    def post(self, request):
        user1 = request.user
        context = {
            'user': user1
        }
        return render(request, 'movies/user_profile.html', context)


class FilterView(TemplateView, LoginRequiredMixin):
    def post(self, request):
        type1 = request.POST.get('genre')
        movies = Movie.objects.filter(genre=type1)
        return render(request, 'movies/index.html', movies)


class SignupView(TemplateView):
    def get(self, request):
        return render(request, 'movies/signup.html')

    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        fname = request.POST.get('first_name')
        lname = request.POST.get('last_name')
        password = request.POST.get('password')
        MyUser.createUser(username, email, fname, lname, password)
        return redirect('movies:index')


class LoginView(TemplateView):

    def get(self, request):
        return render(request, 'movies/login.html')

    def post(self, request):
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                django.contrib.auth.login(request, user)
                return HttpResponseRedirect(reverse("movies:index1"))
            else:
                return render(request, "movies/login.html", {
                    "message": "Invalid Credentials"
                })


class LogoutView(LoginRequiredMixin, TemplateView):
    def post(self, request):
        logout(request)
        return redirect('movies:login')


class SearchView(TemplateView):
    def post(self, request):
        title = request.POST['input']
        try:
            movies = Movie.getMovies(title)
            context = {'movies': movies}
            return render(request, 'movies/search_movie.html', context)
        except Movie.DoesNotExist:
            raise Http404("Movie does not exist")


# -

class GetUser(TemplateView):
    def get(self, request):
        user_list = MyUser.getUsers()
        context = {
            'user_list': user_list,
        }
        return render(request, 'movies/user_list.html', context)


def deleteUser(self, request):
    id1 = request.POST.get('delete')
    MyUser.deleteUserQuery(id1)
    return redirect('movies:allUsers')


class AddUserView(LoginRequiredMixin, TemplateView):
    def get(self, request):
        return render(request, 'movies/add_user.html')

    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        fname = request.POST.get('first_name')
        lname = request.POST.get('last_name')
        password = request.POST.get('password')
        MyUser.createUser(username, email, fname, lname, password)
        return redirect('movies:allUsers')


class EditUserView(LoginRequiredMixin, TemplateView):
    def get(self, request):
        if request.user.is_authenticated:
            id1 = request.POST.get('edit')
            user = MyUser.getUsers(id1)
            context = {
                'user': user
            }
            return render(request, 'movies/update_profile.html', context)

    def post(self, request):
        id1 = request.POST.get('id')
        user = User.objects.get(id=id1)
        name = request.POST.get('username', None)
        email1 = request.POST.get('email', None)
        fname = request.POST.get('first_name', None)
        lname = request.POST.get('last_name', None)
        passcode = request.POST.get('password', None)
        user.username = name
        user.email = email1
        user.password = passcode
        user.firstName = fname
        user.lastName = lname
        user.save()
        return redirect('movies:allUsers')


# -
def GetMovie(request, id1):
    movie = Movie.getMovies(id1)
    context = {
        'movie': movie
    }
    return render(request, 'movies/movie_page.html', context)


class GetMovieView(TemplateView):
    def get(self, request):
        user_list = Movie.getMovies()
        context = {
            'user_list': user_list,
        }
        return render(request, 'movies/index.html', context)


class AddMovieView(LoginRequiredMixin, TemplateView):
    def get(self, request):
        return render(request, 'movies/add_movie.html')

    def post(self, request):
        name = request.POST.get('title', None)
        thumbnail = request.FILES.get('thumbnail')
        video_url = request.POST.get('video_url')
        genre = request.POST.get('genre')
        short_desc = request.POST.get('short_desc')
        long_desc = request.POST.get('long_desc')
        Movie.createMovie(name, thumbnail, video_url, genre, short_desc, long_desc)
        return redirect('movies:index1')


class EditMovieView(LoginRequiredMixin, TemplateView):
    def get(self, request):
        if request.user.is_authenticated:
            id1 = request.POST.get('edit')
            movie1 = Movie.getMovies(id1)
            context = {
                'movies': movie1
            }
            return render(request, 'movies/edit_movie.html', context)

    def post(self, request):
        id1 = request.POST.get('id')
        movies = Movie.objects.get(id=id1)
        title = request.POST.get('title', None)
        url = request.POST.get('video_url', None)
        s_desc = request.POST.get('short_desc', None)
        l_desc = request.POST.get('long_desc', None)
        type1 = request.POST.get('genre', None)
        movies.thumbnail = movies.thumbnail
        movies.name = title
        movies.video_url = url
        movies.short_desc = s_desc
        movies.long_desc = l_desc
        movies.genre = type1
        movies.save()
        return redirect('movies:index1')


def deleteMovie(request):
    id1 = request.POST.get('delete')
    Movie.deleteMovieQuery(id1)
    return redirect('movies:index')


def RateMovie(request):
    rate = request.POST.get('rating')
    return


class password_reset_request(TemplateView):
    def post(self, request):
        if request.method == "POST":
            password_reset_form = PasswordResetForm(request.POST)
            if password_reset_form.is_valid():
                data = password_reset_form.cleaned_data['email']
                associated_users = User.objects.filter(Q(email=data))
                if associated_users.exists():
                    for user in associated_users:
                        subject = "Password Reset Requested"
                        email_template_name = "movies/password/password_reset_email.txt"
                        c = {
                            "email": user.email,
                            'domain': '127.0.0.1:8000',
                            'site_name': 'Website',
                            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                            "user": user,
                            'token': default_token_generator.make_token(user),
                            'protocol': 'http',
                        }
                        email = render_to_string(email_template_name, c)
                        try:
                            send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                        except BadHeaderError:
                            return HttpResponse('Invalid header found.')
                        return redirect("/password_reset/done/")
            password_reset_form = PasswordResetForm()
            return render(request=request, template_name="movies/password/password_reset.html",
                          context={"password_reset_form": password_reset_form})

movies/templates/movies/add_movie.html
{% extends 'movies/base.html' %}
{% load static %}
    <div>
        {% block main %}
            <form action="{% url 'movies:add_movie' %}" class="p-3" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group pt-4" style="width: 50%; margin-top: 50px;">
                    <label>Thumbnail: </label>
                    <input type="file" name="thumbnail">
                </div>
                <div class="form-group" style="width: 50%">
                    <label>Movie Name</label>
                    <input type="text" class="form-control" required name="title">
                </div>

                <div class="form-group pt-3" style="width: 50%">
                    <label for="video_url">Movie URL</label>
                    <input type="url" class="form-control" id="video_url" required name="video_url">
                </div>
                <div class="form-group pt-3">
                    <label for="short_desc">Short Description</label>
                    <input type="text" class="form-control" id="short_desc" required name="short_desc">
                </div>
                <div class="form-group pt-3">
                    <label for="long_desc">Long Description</label>
                    <input type="text" class="form-control" style="height: 100px" id="long_desc" name="long_desc">
                </div>
                <div class="form-group col-md-4">
                    <label for="genre">Genre</label>
                    <select id="genre" name="genre" class="form-control">
                        <option value="Thriller">Action</option>
                        <option value="Comedy">Comedy</option>
                        <option value="Romance">Romance</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <button class="btn btn-outline-info" id="add_movie" type="submit" value="post">Add Movie</button>
                </div>

            </form>
        {% endblock %}
    </div>

movies/templates/movies/add_user.html
{% extends 'movies/base.html' %}
{% load static %}
    <div>
        {% block main %}
            <div  style="width: 50%; padding: 85px; margin-top: 50px; align-items: center">
                <form action="{% url 'movies:createUser' %}" class="p-3" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>First Name</label>
                        <input type="text" required class="form-control" name="first_name">
                    </div>
                    <div class="form-group">
                        <label>Last Name</label>
                        <input type="text" required class="form-control" name="last_name">
                    </div>
                    <div class="form-group">
                        <label>User Name</label>
                        <input type="text" required class="form-control" name="username">
                    </div>
                    <div class="form-group pt-3">
                        <label for="email">Enter Email</label>
                        <input type="email" required class="form-control" id="email" name="email">
                    </div>
                    <div class="form-group pt-3">
                        <label for="password">Password</label>
                        <input type="password" required class="form-control text-muted" id="password" name="password">
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="is_admin" value="is_admin" id="flexCheckChecked">
                        <label class="form-check-label" for="flexCheckChecked">
                            Is Admin
                        </label>
                    </div>
                    <div class="form-group pt-5">
                        <button class="btn btn-outline-info" id="add_movie" type="submit" value="post">Add User</button>
                    </div>

                </form>
            </div>
        {% endblock %}
    </div>

movies/templates/movies/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"><title>Movie Hub</title>
    </head>
    <style>
        body {
            padding: 0;
            margin: 0;
            font-family: 'Montserrat',Helvetica,Arial,Lucida,sans-serif;
        }
        .main {
            background-color: black;
            color: antiquewhite;
        }
        .temp {
            flex: 1;
        }
        .header {
            width: 100%;
            position: fixed;
            top: 0;
            z-index: 555;
            background-color: black;
        }
        .section1 {
            height: 700px;
            width: 100%;
            background-image: url("/movies/static/my_folder_name/movie-bg-1.jpg");
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
        .section1 p{
            font-size: 50px;
            text-align: left;
            width: 60%;
            padding: 100px 100px 20px 100px;
            color: whitesmoke;
        }
        .section1 button{
            margin: 0 100px;
            padding: 15px 25px;
            color: whitesmoke;
        }
        .section2 {
        padding: 100px 50px 200px 200px;
        text-align: center;
        background-color: black;
        min-height: 100vh;
        }

        .footer {
            background-color: black;
            margin-bottom: 0;
            position: relative;
            bottom:0;
        }
    </style>

    <body>
        <div class="main d-flex flex-column">
            <div class="">
                <header class="header">
                    <div class="container-fluid p-2">
                        <nav class="d-flex flex-row navbar navbar-expand-md" >
                            <div class="px-3">
                                <a href="{% url 'movies:index1' %}" class="navbar-brand text-light" style="color: whitesmoke">MOVIES HUB</a>
                            </div>

                            <div class="flex-fill">
                                <ul class="navbar-nav">
                                    <li class="nav-item active">
                                        <a class="nav-link text-light" href="{% url 'movies:index1' %}">Home<span class="sr-only"></span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" href="{% url 'movies:index1' %}">Browse Movies</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" href="{% url 'movies:profile' %}">User Profile</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" style="color: whitesmoke" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Filter Movie
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                            <input type='hidden' name='genre'>
                                            <a class="dropdown-item" href="#">Thriller Movies</a>
                                            <a class="dropdown-item" href="#}">Comedy Movies</a>
                                            <a class="dropdown-item" href="#">Romance Movies</a>
                                        </div>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" href="{% url 'movies:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </div>
                            <div>
                                <form action="{% url 'movies:search' %}" class="row p-1" method="POST">
                                    {% csrf_token %}
                                    <div class="col-sm-8 p-0">
                                        <input class="form-control" name="input" type="search" placeholder="Search" aria-label="Search">
                                    </div>
                                    <div class="col-sm-2 p-0">
                                        <button class="btn btn-outline-info" id="search" type="submit">Search</button>
                                    </div>
                                </form>
                            </div>
                        </nav>
                    </div>
                </header>
            </div>
            <div class="flex-fill temp">
                {% block main %}
                {% endblock %}
            </div>
            <div class="footer text-light">
                <footer class="card-footer text-center">
                    <div class="footer-copyright py-3">© 2017-2018 Company Name</div>
                    <div>
                        <a href="https://google.com/" class="text-light"> Privacy   Terms   Support</a>
                    </div>
                </footer>
            </div>
        </div>
    </body>
</html>

movies/templates/movies/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Login</title>
</head>
<style>
    body {
        padding: 0;
        margin: 0;
        background-color: #202020;
        font-family: 'Montserrat',Helvetica,Arial,Lucida,sans-serif;
    }
    .image {
        width: 50%;
        height: 100vh;
        background-image: url("/movies/static/my_folder_name/pic1.jpg");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    .wrap-login {
        display: flex;
        flex-wrap: wrap;
        align-items: stretch;
        flex-direction: row;
    }
    .form {
        padding: 120px;

        color: antiquewhite;
        margin: 50px 0 100px 0;
    }
    .input {
        width: 100%;
        padding: 30px;
        margin: 10px 0 20px 0;
        border-radius: 10px;
        background-color: transparent;
        text-align: center;
        color: antiquewhite;
        border: 1px solid antiquewhite;
    }
    .heading {
        color: antiquewhite;
        padding: 0 0 20px 0;
        text-align: center;
    }
    .button {
        padding: 10px;
        width: 100%;
    }
    .link {
        padding: 30px;
        text-align: center;
        color: antiquewhite;
    }
    .link a{
        text-decoration: underline;
        color: #B8B8B8;
    }
</style>
<body>

    <div class="wrap-login">
        <div class="col-sm-6 image">

        </div>
        <div class="col-sm-6 form">
            <h2 class="heading">Login To Continue</h2>
            <form action="{% url 'movies:check_user' %}" class="needs-validation" method="POST">
                {% csrf_token %}
                <div class="form-group mt-3">
                    <input type="text" class="form-control input" name="username" required placeholder="Enter Username">
                    <div class="invalid-feedback">
                        Please Enter username.
                    </div>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control input text-muted" required name="password" placeholder="Enter Password">
                    <small  id="passwordHelpInline" class="text-muted">
                        Must be 8-20 characters long.
                    </small>
                </div>
                <div class="">
                    <button class="button btn btn-outline-info w-100 mt-4" type="submit" value="post">
                        Login
                    </button>
                    <p class="link">Click here to <a href="{% url 'movies:signup' %}">Register.</a></p>
                </div>
            </form>
        </div>
    </div>

</body>
</html>

movies/templates/movies/movie_page.html
{% extends 'movies/base.html' %}
{% load static %}
    <div>
        {% block main %}
            <div class="d-flex flex-row" style="padding: 100px 20px; background-color: black; color: whitesmoke">
                <div class="p-5">
                <img class="image" src="{{ movie.thumbnail.url }}" height="315" width="250" />
                </div>

                <div class="p-5" style="margin-top: 50px; text-align: justify">
                    <h2>{{ movie.name }}</h2>
                    <h6>{{ movie.short_desc }}</h6>
                    <br>
                    <p style="font-size: 18px">{{ movie.long_desc }}</p>
                    <div style="margin-top: 2rem;">
                        <h4>Here is the link to watch online:</h4>
                        <a href="{{ movie.video_url }}">{{ movie.video_url }}</a>
                    </div>
                </div>
                    <form action="{% url 'movies:edit_movie' %}" class="p-3" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-outline-info" type="submit">Edit</button>
                         <input type="hidden" id="edit" name="edit" value="{{ movie.id }}">
                    </form>
                    <form action="{% url 'movies:deleteMovie' %}" class="pt-3" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-outline-info" type="submit">Delete</button>
                        <input type="hidden" id="delete" name="delete" value="{{ movie.id }}">
                    </form>
                </div>
                <div>
                    <form action="{% url 'movies:rating' %}" class="pt-3" method="POST">
                        {% csrf_token %}
                        <input type="hidden" id="rating" name="rating" value="{{ movie.id }}">
                        <label for="rating">Rate the Movie:</label>
                            <select id="rating" name="rating" class="form-control">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                    </form>
                </div>
            </div>
        {% endblock %}
    </div>

movies/templates/movies/user_list.html
{% extends 'movies/base.html' %}
<style>
    .section2 {
        text-align: center;
        background-color: black;
    }
    .movbar {
        border: 1px solid #264b5d;
    }
</style>
{% block main %}
<div class="main">
    <section class="main-content p-5 mt-5">
        <div>
            <form action="{% url 'movies:createUser' %}" style="padding-right: 20px" method="POST">
                {% csrf_token %}
                <button class="btn btn-outline-info" style="float: right" type="submit"> ADD USER </button>
            </form>
        </div>
        {% if user_list %}
        <div class="d-flex flex-column">
            {% for users in user_list %}
            <div class="row border p-3 m-3">
                <div class="col-sm-9 m-3 p-2">
                    <a href="{{ users.id }}">
                        <h4 class="card-title text-light">{{ users.username }}</h4>
                    </a>
                    <p class=" text-light">{{ users.firstName }}</p>
                    <p class=" text-light">{{ users.lastName }}</p>
                    <p class=" text-light">{{ users.email }}</p>
                </div>
                <div class="col m-3 p-2">
                    <form action="{% url 'movies:edit_user' %}" class="pt-3" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-outline-info" type="submit">EDIT</button>
                        <input type="hidden" id="edit" name="edit" value="{{ users.id }}">
                    </form>
                    <form action="{% url 'movies:deleteUser' %}" class="pt-3" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-outline-info" type="submit">Delete</button>
                        <input type="hidden" id="delete" name="delete" value="{{ users.id }}">
                    </form>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </section>

</div>
{% endblock %}